"""add ip_address to comments

Revision ID: 7eadb73cdd14
Revises: 7a1b5d8f3d9e
Create Date: 2025-04-30 15:08:12.275880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7eadb73cdd14'
down_revision: Union[str, None] = '7a1b5d8f3d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('comments', 'article_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'article_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('comments', 'ip_address')
    # ### end Alembic commands ###
