/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ArticleCard: typeof import('./components/ArticleCard.vue')['default']
    ArticleForm: typeof import('./components/ArticleForm.vue')['default']
    CommentSection: typeof import('./components/CommentSection.vue')['default']
    FaviconIcon: typeof import('./components/icons/FaviconIcon.vue')['default']
    ImagePicker: typeof import('./components/ImagePicker.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    LogoIcon: typeof import('./components/icons/LogoIcon.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonLoader: typeof import('./components/SkeletonLoader.vue')['default']
    TreeBackground: typeof import('./components/TreeBackground.vue')['default']
  }
}
